[package]
name = "croc-sidecar"
version = "0.2.4"
authors = ["Márcio Sobel"]
description = "A wrapper for the Croc binary"
repository = "https://github.com/marciosobel/croc-sidecar"
readme = "readme.md"
documentation = "https://docs.rs/croc-sidecar"
keywords = ["wrapper", "croc"]
license = "MIT"
edition = "2024"

[dependencies]
futures-util = "0.3.32"
thiserror = "2.0.18"
tokio = { version = "1.51.0", features = ["process", "io-util"] }
serde = { version = "1.0.228", optional = true }

[features]
serde = ["dep:serde", "serde/derive"]

[dev-dependencies]
tokio = { version = "1.51.0", features = ["fs", "macros", "rt", "rt-multi-thread"] }
